
#
# This LookML file was generated by AtScale on 2022-01-25T16:34:05.747518Z
#
# AtScale engine version: 2021.4.0.11186
# AtScale DesignCenter version: 2021.4.0.18787
# AtScale version: 2021.4.0.4227
# Organization: default
# Project: Workshop_DG

connection: "dg"
label: "Workshop_DG"


include: "/views/Workshop__DG/Workshop__DG.view.lkml"


explore: Workshop_DG {
  label: "Workshop_DG"
}

